#version: '3.8'

services:
  # MySQL container
  db:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: EduTech
      MYSQL_USER: root
      MYSQL_PASSWORD: password123A@
      MYSQL_ROOT_PASSWORD: password123A@

  # Spring Boot container
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
